module OpenAPI
  module Client
    # Request/response helpers for client classes generated by `ClientGenerator`.
    # Include this module in your client implementation class.
    module Helpers
      # Serializes body as JSON. Returns a (body_string, content_type) pair.
      private def serialize_json_body(body) : {String, String}
        {body.to_json, "application/json"}
      end

      # Serializes body as YAML. Returns a (body_string, content_type) pair.
      private def serialize_yaml_body(body) : {String, String}
        {body.to_yaml, "application/yaml"}
      end

      # Serializes body as form-encoded. Returns a (body_string, content_type) pair.
      private def serialize_form_body(body) : {String, String}
        {body.to_form_params, "application/x-www-form-urlencoded"}
      end

      # Serializes body as multipart/form-data. Returns an (io, content_type) pair.
      # The content_type includes the boundary parameter required by HTTP.
      private def serialize_multipart_body(body) : {IO::Memory, String}
        io = IO::Memory.new
        builder = HTTP::FormData::Builder.new(io)
        body.to_multipart(builder)
        builder.finish
        {io.rewind, "multipart/form-data; boundary=#{builder.boundary}"}
      end

      # Serializes body as XML. Returns a (body_string, content_type) pair.
      private def serialize_xml_body(body) : {String, String}
        {body.to_xml, "application/xml"}
      end

      # Serializes body to a (body_string, content_type) pair based on a runtime
      # content_type hint. Uses YAML when content_type includes "yaml" but not "json",
      # form-encoding when it includes "x-www-form-urlencoded", JSON otherwise.
      # Use only when the body type includes OpenAPI::Form::Serializable.
      private def serialize_body(body, content_type : String) : {String, String}
        if content_type.includes?("yaml") && !content_type.includes?("json")
          {body.to_yaml, "application/yaml"}
        elsif content_type.includes?("x-www-form-urlencoded")
          {body.to_form_params, "application/x-www-form-urlencoded"}
        else
          {body.to_json, "application/json"}
        end
      end

      # Serializes body as YAML or JSON (no form, no XML).
      # Use when the operation supports JSON and YAML but not form or XML.
      private def yaml_json_serialize_body(body, content_type : String) : {String, String}
        if content_type.includes?("yaml") && !content_type.includes?("json")
          {body.to_yaml, "application/yaml"}
        else
          {body.to_json, "application/json"}
        end
      end

      # Serializes body as XML or JSON.
      # Use when the operation supports JSON and XML but not YAML or form.
      private def xml_json_serialize_body(body, content_type : String) : {String, String}
        if content_type.includes?("xml")
          {body.to_xml, "application/xml"}
        else
          {body.to_json, "application/json"}
        end
      end

      # Executes *request* via the injected HTTP client.
      # Override in a subclass to add logging, auth headers, retries, or any other
      # cross-cutting behaviour. Call `super` to forward the (possibly mutated) request,
      # or re-implement the HTTP call entirely.
      private def perform_request(operation : Symbol, request : HTTP::Request) : HTTP::Client::Response
        @http.exec(request)
      end

      # Adds *key*=*value* to *p* unless *value* is nil. Handles `.to_s` internally.
      private def add_param(p : HTTP::Params::Builder, key : String, value : T) : Nil forall T
        p.add(key, value.to_s) unless value.nil?
      end

      # Adds one *key*=*element* entry per element (OAS `style: form, explode: true`).
      private def add_exploded_param(p : HTTP::Params::Builder, key : String, values : Array(T)?) : Nil forall T
        return if values.nil?
        values.each { |v| p.add(key, v.to_s) }
      end

      # Joins *values* with *delimiter* and adds a single *key*=joined entry
      # (OAS `explode: false` with `form`/`spaceDelimited`/`pipeDelimited` styles).
      private def add_joined_param(p : HTTP::Params::Builder, key : String, values : Array(T)?, delimiter : String) : Nil forall T
        return if values.nil? || values.empty?
        p.add(key, values.map(&.to_s).join(delimiter))
      end

      # Builds a URL from *path* and one or more query strings, joining non-empty
      # parts with "&" and appending them after "?". Returns *path* unchanged when
      # all parts are empty.
      private def build_url(path : String, *parts : String) : String
        combined = parts.reject(&.empty?).join("&")
        combined.empty? ? path : "#{path}?#{combined}"
      end

      # Deserializes a JSON response body.
      private def parse_json_response(response : HTTP::Client::Response, type : T.class) : T forall T
        T.from_json(response.body)
      end

      # Deserializes a YAML response body.
      private def parse_yaml_response(response : HTTP::Client::Response, type : T.class) : T forall T
        T.from_yaml(response.body)
      end

      # Deserializes an XML response body.
      private def parse_xml_response(response : HTTP::Client::Response, type : T.class) : T forall T
        T.from_xml(response.body)
      end

      # Deserializes response body as YAML or JSON based on Content-Type.
      # Use for operations that return YAML and JSON but not XML.
      private def yaml_json_parse_typed_response(response : HTTP::Client::Response, type : T.class) : T forall T
        ct = response.headers["Content-Type"]?
        if ct && ct.includes?("yaml") && !ct.includes?("json")
          T.from_yaml(response.body)
        else
          T.from_json(response.body)
        end
      end

      # Deserializes response body as XML or JSON based on Content-Type.
      # Use for operations that return XML and JSON but not YAML.
      private def xml_json_parse_typed_response(response : HTTP::Client::Response, type : T.class) : T forall T
        ct = response.headers["Content-Type"]?
        if ct && ct.includes?("xml")
          T.from_xml(response.body)
        else
          T.from_json(response.body)
        end
      end

      # Deserializes response body using JSON, YAML, or XML based on Content-Type.
      # Use for operations that return all three content types.
      private def parse_typed_response(response : HTTP::Client::Response, type : T.class) : T forall T
        ct = response.headers["Content-Type"]?
        if ct && ct.includes?("yaml") && !ct.includes?("json")
          T.from_yaml(response.body)
        elsif ct && ct.includes?("xml")
          T.from_xml(response.body)
        else
          T.from_json(response.body)
        end
      end
    end
  end
end
