require "./helpers"

module OpenAPI
  module Server
    # Request/response helpers for handler classes generated by `KemalServerGenerator`.
    # Include this module in your handler implementation class.
    module KemalHelpers
      include Helpers

      private def query_string(env, name : String, default : String? = nil) : String?
        env.params.query[name]? || default
      end

      private def query_int32(env, name : String, default : Int32? = nil) : Int32?
        env.params.query[name]?.try(&.to_i32?) || default
      end

      private def query_int64(env, name : String, default : Int64? = nil) : Int64?
        env.params.query[name]?.try(&.to_i64?) || default
      end

      private def query_float32(env, name : String, default : Float32? = nil) : Float32?
        env.params.query[name]?.try(&.to_f32?) || default
      end

      private def query_float64(env, name : String, default : Float64? = nil) : Float64?
        env.params.query[name]?.try(&.to_f64?) || default
      end

      private def query_bool(env, name : String, default : Bool? = nil) : Bool?
        env.params.query[name]?.try { |v| v == "true" } || default
      end

      # Returns all values for repeated keys (OAS `style: form, explode: true`).
      # Pass a *delimiter* string to split a single value instead (explode: false).
      private def query_string_array(env, name : String, delimiter : String? = nil) : Array(String)?
        if d = delimiter
          env.params.query[name]?.try(&.split(d)).presence
        else
          vals = env.params.query.fetch_all(name)
          vals.empty? ? nil : vals
        end
      end

      private def path_string(env, name : String) : String
        env.params.url[name]
      end

      private def path_int32(env, name : String) : Int32?
        env.params.url[name]?.try(&.to_i32?)
      end

      private def path_int64(env, name : String) : Int64?
        env.params.url[name]?.try(&.to_i64?)
      end

      private def path_float32(env, name : String) : Float32?
        env.params.url[name]?.try(&.to_f32?)
      end

      private def path_float64(env, name : String) : Float64?
        env.params.url[name]?.try(&.to_f64?)
      end
    end
  end
end
