require "./helpers"

module OpenAPI
  module Server
    # Request/response helpers for handler classes generated by `MuxServerGenerator`.
    # Include this module in your handler implementation class.
    module MuxHelpers
      include Helpers

      private def query_string(ctx, name : String, default : String? = nil) : String?
        ctx.request.query_params[name]? || default
      end

      private def query_int32(ctx, name : String, default : Int32? = nil) : Int32?
        ctx.request.query_params[name]?.try(&.to_i32?) || default
      end

      private def query_int64(ctx, name : String, default : Int64? = nil) : Int64?
        ctx.request.query_params[name]?.try(&.to_i64?) || default
      end

      private def query_float32(ctx, name : String, default : Float32? = nil) : Float32?
        ctx.request.query_params[name]?.try(&.to_f32?) || default
      end

      private def query_float64(ctx, name : String, default : Float64? = nil) : Float64?
        ctx.request.query_params[name]?.try(&.to_f64?) || default
      end

      private def query_bool(ctx, name : String, default : Bool? = nil) : Bool?
        ctx.request.query_params[name]?.try { |v| v == "true" } || default
      end

      # Returns all values for repeated keys (OAS `style: form, explode: true`).
      # Pass a *delimiter* string to split a single value instead (explode: false).
      private def query_string_array(ctx, name : String, delimiter : String? = nil) : Array(String)?
        if d = delimiter
          ctx.request.query_params[name]?.try { |v| vals = v.split(d); vals.empty? ? nil : vals }
        else
          vals = ctx.request.query_params.fetch_all(name)
          vals.empty? ? nil : vals
        end
      end

      private def path_string(ctx, name : Symbol) : String
        ctx.request.path_param(name)
      end

      private def path_int32(ctx, name : Symbol) : Int32
        ctx.request.path_param(name).to_i32
      end

      private def path_int64(ctx, name : Symbol) : Int64
        ctx.request.path_param(name).to_i64
      end

      private def path_float32(ctx, name : Symbol) : Float32
        ctx.request.path_param(name).to_f32
      end

      private def path_float64(ctx, name : Symbol) : Float64
        ctx.request.path_param(name).to_f64
      end

      private def path_uuid(ctx, name : Symbol) : UUID
        UUID.new(ctx.request.path_param(name))
      end
    end
  end
end
