module OpenAPI
  module Generator
    # :nodoc:
    abstract class Base
      abstract def generate(doc : Model::Document, ctx : RenderContext) : Array(GeneratedFile)

      protected def emit_header(doc : Model::Document, ctx : RenderContext, b : Crystina::Builder) : Nil
        b.comment("Generated by #{File.basename(PROGRAM_NAME)} - do not edit manually.")
        b.comment("Generated using threez/openapi.cr@#{OpenAPI::VERSION} based on the source of:")
        if source = ctx.source_file
          b.comment("#{File.basename(source)} (#{doc.info.title} #{doc.info.version})")
        else
          b.comment("#{doc.info.title} #{doc.info.version}")
        end
        b.blank
      end
    end
  end
end
